# This will do the same as Java CI build for develop, but this one is for manual purpose on specific branch.

name: Java CI - manual for branch

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file Realization/backend/aggregator/pom.xml -Prelease -DdocumentationOnly=true
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: idm.war
        path: Realization/backend/app/target
